version: '3.8'
services:

  rigctld:
    image: registry.gitlab.com/librespacefoundation/docker-hamlib/hamlib
    user: '999'
    read_only: true
    environment:
      MODEL: '1'
    restart: 'unless-stopped'
    command: 'rigctld'

  rotctld:
    image: registry.gitlab.com/librespacefoundation/docker-hamlib/hamlib
    user: '999'
    read_only: true
    environment:
      MODEL: '1'
      SET_CONF: 'min_az=0,max_az=360,min_el=0,max_el=180'
    device_cgroup_rules:
      - 'c 188:* rwm'
    
    restart: 'unless-stopped'
    command: 'rotctld'
    stop_grace_period: 1s

  satnogs_client:
    #image: librespace/satnogs-client:master  # SatNOGS stable docker image
    #image: librespace/satnogs-client:master-unstable  # SatNOGS experimental docker image
    #image: knegge/satnogs-client:lsf-dev-addons
    #image: knegge/satnogs-client:lsf-addons
    #image: knegge/satnogs-client:sa2kng-addons
    image: knegge/satnogs-client:sa2kng
    
    user: '999'
    #read_only: true
    init: true # init is needed when lauching processes in the background
    env_file:
      - ./station.env
    environment:
      SATNOGS_RIG_IP: 'rigctld'
      SATNOGS_RIG_PORT: '4532'
    #  SATNOGS_ROT_MODEL: 'ROT_MODEL_xxxx'
    #  SATNOGS_ROT_PORT: 'dev'
    #  SATNOGS_ROT_BAUD: '9600'
    #  SATNOGS_ROT_THRESHOLD: '4'

    #command: 'satnogs-client' # default
    command: 'liveupdate-satyaml.sh satnogs-client'
    device_cgroup_rules:
      - 'c 189:* rwm'
    devices:
      - '/dev/bus/usb'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'volume'
        source: 'satnogs-client'
        target: '/var/lib/satnogs-client'
    restart: 'unless-stopped'
    stop_grace_period: 1s

volumes:
  satnogs-client: # persistent named volume for the station

